// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmOhqtn9PllsShvEHKaUB3ZMNQPecN4cw',
    appId: '1:1070200427132:web:5a40118caada3511ffaff9',
    messagingSenderId: '1070200427132',
    projectId: 'tiktockclonepankajkcodes',
    authDomain: 'tiktockclonepankajkcodes.firebaseapp.com',
    storageBucket: 'tiktockclonepankajkcodes.appspot.com',
    measurementId: 'G-3BG3E27LMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3pSMB7JMVSYcJawKC8PAwChI5iVu7HA',
    appId: '1:1070200427132:android:5b3b05cd6ea79370ffaff9',
    messagingSenderId: '1070200427132',
    projectId: 'tiktockclonepankajkcodes',
    storageBucket: 'tiktockclonepankajkcodes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEc5OlCaoWA6T-KwBh0MAoKBMGCdlXjdU',
    appId: '1:1070200427132:ios:3c4df3ec22f379f1ffaff9',
    messagingSenderId: '1070200427132',
    projectId: 'tiktockclonepankajkcodes',
    storageBucket: 'tiktockclonepankajkcodes.appspot.com',
    iosClientId: '1070200427132-ibcatb367ghoo88nmagomlon8jusa6f8.apps.googleusercontent.com',
    iosBundleId: 'com.pankajkcodes.tiktokclone',
  );
}
